name: rig_workspace
publish_to: none
environment:
  sdk: ^3.13.0
workspace:
  - packages/rig
  - packages/rig_cli
  - packages/rig_mysql
  - packages/rig_postgres
  - packages/rig_redis
  - examples/basic-sample
